# Generated by Django 3.2.9 on 2021-12-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce_api", "0002_auto_20211202_0937"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="firstname",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
